FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir \
    "mlflow>=3.8.1" \
    psycopg2-binary \
    boto3

EXPOSE 5000

ENTRYPOINT ["mlflow"]
CMD ["server"]
